version: "3.7"


services:

  mongo-db:
    image: mongo
    container_name: mongo-docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d
